apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "p110-exporter.fullname" . }}
  labels:
    {{- include "p110-exporter.labels" . | nindent 4 }}
data:
  tapo.yaml: |
{{ .Values.config.devicesConfig | indent 4 }}
