{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "p110-exporter.fullname" . }}
  labels:
    {{- include "p110-exporter.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "p110-exporter.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: http
    interval: {{ .Values.podMonitor.interval }}
    scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
    {{- with .Values.podMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.podMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
