{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "p110-exporter.fullname" . }}
  labels:
    {{- include "p110-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  tapo-email: {{ .Values.config.tapoEmail | quote }}
  tapo-password: {{ .Values.config.tapoPassword | quote }}
{{- end }}
